Numpy : Practice Problem

1. Extract all odd numbers from arr


In [3]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [5]:
# Q1 solution
arr[arr%2!=0]


array([1, 3, 5, 7, 9])

2. Replace all odd numbers in arr with -1

In [169]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [170]:
# Q2 solution
arr[arr%2==1]= -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

3. Convert a 1D array to a 2D array with 2 rows

In [32]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
# Q3solution
np.reshape(arr,(2,-1))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

4. Stack arrays a and b vertically

In [100]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [41]:
# Q4 solution 
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

5. Get all items between 5 and 10 from a

In [174]:
a = np.array([2, 6, 1, 9, 10, 3, 27])


In [175]:
#Q5 solution
a[(a>5)&(a<11)]

array([ 6,  9, 10])

Desired Output:
(array([6, 9, 10]),)

6. Create a null vector of size 10 but the fifth value which is 1.

In [58]:
# Q6 solution
a=np.zeros(10,int)
a
a[4]=1
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

7. Create a vector with values ranging from 10 to 49.

In [65]:
# Q7 solution
a=np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

8. Create a 10x10 array with random values and find the minimum and maximum values.

In [84]:
# # Q8 solution
a=np.random.randint(1,60,(10,10))
print(a)
print('maximum value is',np.max(a))
print('minimum value in a is ',np.min(a))

[[26 45 35 38 38 30 54 13 37 16]
 [15 33 16 35 32 57 49 30 11 46]
 [43  4 47 50 32 29  6 45 41 54]
 [19 17 17 15 29  5 55 35 56 35]
 [45 17 23 39 35 38 11  9 34 30]
 [32 32 17 55  7 50 33  3 33  9]
 [37 52  7 53 20 25 34 49 12 14]
 [51 30 36  9 59  4  6 52 48 14]
 [ 4 24 57 18 51 18 32 40 55 44]
 [19 45 19 21 29 59 31 50 37 56]]
maximum value is 59
minimum value in a is  3


9. Create a 3*3 matrix and print it's transpose matrix

In [104]:
# # Q9  solution
arr=np.arange(9).reshape(3,3)
print('arr  is\n',arr)
print('transpose of arr is \n',arr.T)

arr  is
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
transpose of arr is 
 [[0 3 6]
 [1 4 7]
 [2 5 8]]


10. Create two arrays of 2-D and find dot product of it.

In [113]:
# Q10 solution
arr_1=np.arange(4).reshape(2,2)
arr_2=np.arange(4).reshape(2,2)
print(np.dot(arr_1,arr_2))

[[ 2  3]
 [ 6 11]]


11. Compute the maximum for each row in the given array.

In [121]:
# Q11 solution
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(a)
print('maximum marks of each row are ',np.max(a,axis=1))

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]
maximum marks of each row are  [9 8 6 3 9]


12. Select 3rd & 5th row and 3rd & 4th columns

In [122]:
data = np.random.randint(10,100,(5,4))
data

array([[25, 70, 68, 26],
       [19, 96, 12, 37],
       [14, 41, 11, 23],
       [93, 14, 69, 77],
       [17, 59, 57, 75]])

In [127]:
# Q12 solution
data[[2,4],2:4]

array([[11, 23],
       [57, 75]])

13. Convert below matrix into vector

In [129]:
matrix = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])

In [140]:
# Q13 solution
np.reshape(matrix,(1,-1))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

14. The product of two inverse matrix is identical matrix,prove

In [145]:
# create a square matrix
m = np.array([[2,3],
              [2,4]])

In [148]:
# Q14 solution
n=np.linalg.inv(m)

In [149]:
np.dot(m,n)

array([[1., 0.],
       [0., 1.]])

15. Create a matrix from a uniform distribution over [0, 1)

In [153]:
# Q15 solution
arr=np.random.rand(2,3)
arr

array([[0.29887635, 0.56874553, 0.17862432],
       [0.5325737 , 0.64669147, 0.14206538]])